version: '3'
services:
  cc:
    build: .
    ports:
     - "8883:8883"
    environment:
     - CC_REDIS=redis
     - CC_UPDATE_TIME=60
    depends_on:
     - "redis"
  redis:
    image: "redis:alpine"